name: whatsapp_clone
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  agora_uikit: ^1.3.10
  audioplayers: ^6.0.0
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.2
  contacts_service: ^0.6.3
  country_picker: ^2.0.25
  country_pickers: ^2.0.0
  cupertino_icons: ^1.0.6
  emoji_picker_flutter: ^2.2.0
  equatable: ^2.0.5
  file_picker: ^8.0.3
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_contacts: ^1.1.7+1
  flutter_pin_code_fields: ^2.2.0
  flutter_story_view: ^0.0.4
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  get_time_ago: ^1.3.1
  giphy_picker: ^3.0.2
  image_picker: ^1.1.1
  intl: ^0.19.0
  just_audio: ^0.9.37
  path_provider: ^2.1.3
  swipe_to: ^1.0.6
  uuid: ^4.4.0
  video_player: ^2.8.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
